Add additional space before font-family if needed
cssnano/cssnano pull request #1520
Opened 2023-08-18 15:37 UTC by smelukov

`.8em"YS Text", Arial, Helvetica, sans-serif` => `.8em YS Text, Arial, Helvetica, sans-serif`

See #1519

2023-08-21 10:53 UTC, smelukov commented
friendly ping ☺️

2023-08-22 14:07 UTC, SedykhArtem approved these changes

2023-10-08 17:38 UTC, ludofischer requested changes
Thank you for your PR and sorry for taking so long to review it. It looks fine but could you solve the TypeScript issue?

2023-10-08 17:38 UTC, ludofischer commented on packages/postcss-minify-font-values/src/lib/minify-font.js
> +    // @ts-ignore
I don't think we use `ts-ignore` anywhere else. Could you find a way to solve this through an additional check or a TypeScript cast?

2023-10-08 17:41 UTC, ludofischer commented on packages/postcss-minify-font-values/src/lib/minify-font.js
> +    // @ts-ignore
The tests do not pass either, there's likely too many assumptions about the shape of the nodes here.

2024-02-24 10:42 UTC, closed without merging